services:
  api:
    build:
      context: .
    image: pool-api:latest
    container_name: pool-api
    ports: ["8487:8000"]
    restart: unless-stopped
    environment:
      DEVELOPMENT_MODE: "prod"
      AWS_PROFILE: "default"
      AWS_SDK_LOAD_CONFIG: "1"
    healthcheck:
      test: ["CMD-SHELL", "python healthcheck.py"]
      interval: 5s
      timeout: 3s
      start_period: 3s
      retries: 20
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
    networks:
      - appnet

networks:
  appnet:
    external: true
